# Configuration file of Oort training experiment

# ========== Cluster configuration ========== 
# ip address of the parameter server (need 1 GPU)
# ps_ip: dev-amd20-v100
# ps_ip: 192.168.10.146
ps_ip: dev-amd20-v100
# ip address of each worker:# of gpus on this worker
# Note that if we collocate ps and worker, then we need to decrease this number of gpus by 1
# E.g., master node has 4 GPUs, then 1 for the ps, and worker should be set to: worker:3
worker_ips: 
    # - dev-amd20-v100:[0,1,1,1,1,1]
    # - dev-amd20-v100:[0,2]
    # - dev-amd20-v100:[0,0,1,0,1,1,1,1]
    - dev-amd20-v100:[0,1,1,1]

exp_path: /mnt/home/lichenni/projects/mobicom22_fl/training

python_path: /mnt/home/lichenni/anaconda3/envs/oort/bin/

auth:
    ssh_user: "lichenni"
    ssh_private_key: ~/.ssh/id_rsa

# cmd to run before we can indeed run oort (in order)
setup_commands:
    # - source $HOME/anaconda3/bin/activate oort
    # - export NCCL_SOCKET_IFNAME='ib0'      
    # - export NCCL_SOCKET_IFNAME='enp94s0f0'         # Run "ifconfig" to ensure the right NIC for nccl if you have multiple NICs

# ========== Additional job configuration ========== 
# Default parameters are specified in argParser.py, wherein more description of the parameter can be found

job_conf: 
    - job_name: google_speech               # Generate logs under this folder: log_path/job_name/time_stamp
    - log_path: /mnt/home/lichenni/projects/mobicom22_fl/training/evals # Path of log files
    - total_worker: 50                     # Number of participants per round, we use K=100 in our paper, large K will be much slower
    - data_set: google_speech                     # Dataset: openImg, google_speech, stackoverflow
    - data_dir: /mnt/ufs18/nodr/home/lichenni/projects/FedScale/dataset/google_speech    # Path of the dataset
    - data_mapfile: /mnt/ufs18/nodr/home/lichenni/projects/FedScale/dataset/google_speech/clientDataMap              # Allocation of data to each client, turn to iid setting if not provided
    - client_path: /mnt/ufs18/nodr/home/lichenni/projects/FedScale/dataset/data/device_info/client_device_capacity 
    - user_trace: /mnt/ufs18/nodr/home/lichenni/projects/FedScale/dataset/data/device_info/client_behave_trace
    - sample_mode: random                                  # Client selection: random, oort
    - model: resnet34                            # Models: shufflenet_v2_x2_0, mobilenet_v2, resnet34, albert-base-v2
    - gradient_policy: yogi                 
    # - proxy_avg: True # Commenting out these two lines will turn to "FedAvg"
    - round_penalty: 2.0                    # Penalty factor in our paper (\alpha), \alpha -> 0 turns to (Oort w/o sys)
    - eval_interval: 10                    # How many rounds to run a testing on the testing set
    - epochs: 1000                           # Number of rounds to run this training. We use 1000 in our paper, while it may converge w/ ~400 rounds
    - task: speech
    - pacer_delta: 30                       # Set to include the next WxK clients
    - filter_less: 30                       # Remove clients w/ less than 16 samples
    - batch_size: 16
    - decay_epoch: 15
    - round_threshold: 40                   # the first W * K
    - cut_off_util: 0.4                     # Determined by W * K
    - upload_epoch: 5
    # - enable_adapt_local_epoch: True
    # - enable_dropout: True
    # - enforce_random: True
